data("trees")
summary(trees)
tree_scale<-scale(trees)
tree_scale<-as.data.frame(tree_scale)
lm1 <- lm(Volume~Girth+Height, data=tree_scale)
summary(lm1)
library(car)
vif(lm1)
lm1 <- lm(Volume~Girth*Height, data=tree_scale)
summary(lm1)
